const { contextBridge, ipcRenderer } = require('electron');
const inv = (ch, ...a) => ipcRenderer.invoke(ch, ...a);

contextBridge.exposeInMainWorld('api', {
  db: {
    exportFile: ()          => inv('db:exportFile'),
    importFileMerge: ()     => inv('db:importFileMerge'),
  },
  folder: {
    getAll:  ()            => inv('folder:getAll'),
    create:  (n,m,c)       => inv('folder:create', n,m,c),
    update:  (id,n,m,c)    => inv('folder:update', id,n,m,c),
    delete:  (id)          => inv('folder:delete', id),
  },
  project: {
    getAll:  (fid)         => inv('project:getAll', fid),
    get:     (id)          => inv('project:get', id),
    create:  (data)        => inv('project:create', data),
    update:  (id,data)     => inv('project:update', id, data),
    delete:  (id)          => inv('project:delete', id),
    getDesc: (pid)         => inv('project:getDesc', pid),
    addDesc: (pid,n,t)     => inv('project:addDesc', pid,n,t),
    updDesc: (id,n,t)      => inv('project:updDesc', id,n,t),
    delDesc: (id)          => inv('project:delDesc', id),
    getTags: (pid)        => inv('project:getTags', pid),
    setTags: (pid,tags)   => inv('project:setTags', pid,tags),
    addTag: (pid,tid)     => inv('project:addTag', pid,tid),
    removeTag: (pid,tid)  => inv('project:removeTag', pid,tid),
    getAllUsedTags: (pid)  => inv('project:getAllUsedTags', pid),
  },
  category: {
    getAll:  (pid)         => inv('category:getAll', pid),
    create:  (pid,n,c)     => inv('category:create', pid,n,c),
    update:  (id,n,c)      => inv('category:update', id,n,c),
    delete:  (id)          => inv('category:delete', id),
  },
  template: {
    getAll:  (cid)         => inv('template:getAll', cid),
    create:  (cid,d,t)     => inv('template:create', cid,d,t),
    update:  (id,d,t)      => inv('template:update', id,d,t),
    delete:  (id)          => inv('template:delete', id),
  },
  object: {
    getAll:  (cid)         => inv('object:getAll', cid),
    get:     (id)          => inv('object:get', id),
    create:  (pid,cid,n,c) => inv('object:create', pid,cid,n,c),
    update:  (id,n,c)      => inv('object:update', id,n,c),
    updateNote: (id,note)  => inv('object:updateNote', id,note),
    delete:  (id)          => inv('object:delete', id),
    getAttrs:(oid)         => inv('object:getAttrs', oid),
    upsertAttr:(oid,tid,v) => inv('object:upsertAttr', oid,tid,v),
    getCategoryAttrs:(cid) => inv('object:getCategoryAttrs', cid),
    getTags: (oid)         => inv('object:getTags', oid),
    setTags: (oid,tags)    => inv('object:setTags', oid,tags),
    addTag: (oid,tid)      => inv('object:addTag', oid,tid),
    removeTag: (oid,tid)   => inv('object:removeTag', oid,tid),
  },
  timeline: {
    getAll:  (pid)        => inv('timeline:getAll', pid),
    create:  (pid,n,c)    => inv('timeline:create', pid,n,c),
    update:  (id,n,c)     => inv('timeline:update', id,n,c),
    delete:  (id)         => inv('timeline:delete', id),
    getOrCreateDate: (d,m,y,hh,mm) => inv('timeline:getOrCreateDate', d,m,y,hh,mm),
    getEvents: (tlid)     => inv('timeline:getEvents', tlid),
    createEvent: (tlid,n,s,e,c,story) => inv('timeline:createEvent', tlid,n,s,e,c,story),
    updateEvent: (id,n,s,e,c,story)  => inv('timeline:updateEvent', id,n,s,e,c,story),
    updateEventStory: (id,story) => inv('timeline:updateEventStory', id,story),
    deleteEvent: (id)     => inv('timeline:deleteEvent', id),
    getEventTags: (eid)   => inv('timeline:getEventTags', eid),
    setEventTags: (eid,tags) => inv('timeline:setEventTags', eid,tags),
    addEventTag: (eid,tid) => inv('timeline:addEventTag', eid,tid),
    removeEventTag: (eid,tid) => inv('timeline:removeEventTag', eid,tid),
  },
  relation: {
    getTypes: ()          => inv('relation:getTypes'),
    createType: (n,c)     => inv('relation:createType', n,c),
    updateType: (id,n,c)  => inv('relation:updateType', id,n,c),
    deleteType: (id)      => inv('relation:deleteType', id),
    getOBOB: (pid)        => inv('relation:getOBOB', pid),
    createOBOB: (pid,tid,c,f,t) => inv('relation:createOBOB', pid,tid,c,f,t),
    deleteOBOB: (id)      => inv('relation:deleteOBOB', id),
    update: (id,tid,c)     => inv('relation:update', id,tid,c),
    getOBTL: (pid)        => inv('relation:getOBTL', pid),
    createOBTL: (pid,tid,c,f,t) => inv('relation:createOBTL', pid,tid,c,f,t),
    deleteOBTL: (id)      => inv('relation:deleteOBTL', id),
    getTLTL: (pid)        => inv('relation:getTLTL', pid),
    createTLTL: (pid,tid,c,f,t) => inv('relation:createTLTL', pid,tid,c,f,t),
    deleteTLTL: (id)      => inv('relation:deleteTLTL', id),
    getProjectObjects: (pid) => inv('relation:getProjectObjects', pid),
    getProjectEvents: (pid)  => inv('relation:getProjectEvents', pid),
  },
  map: {
    getAll: (pid)            => inv('map:getAll', pid),
    create: (pid,n,c)        => inv('map:create', pid,n,c),
    update: (id,n,c)         => inv('map:update', id,n,c),
    delete: (id)             => inv('map:delete', id),
    getAreas: (mid)          => inv('map:getAreas', mid),
    createArea: (mid,n,c)    => inv('map:createArea', mid,n,c),
    updateArea: (id,n,c)     => inv('map:updateArea', id,n,c),
    deleteArea: (id)         => inv('map:deleteArea', id),
    getPoints: (aid)         => inv('map:getPoints', aid),
    setPoints: (aid,points)  => inv('map:setPoints', aid, points),
  },
  hashtag: {
    getAll:  ()           => inv('hashtag:getAll'),
    create:  (n,c)        => inv('hashtag:create', n,c),
    update:  (id,n,c)     => inv('hashtag:update', id,n,c),
    delete:  (id)         => inv('hashtag:delete', id),
    getObjectsByTag: (tagId, projectId) => inv('hashtag:getObjectsByTag', tagId, projectId),
    getEventsByTag: (tagId, projectId)  => inv('hashtag:getEventsByTag', tagId, projectId),
  },
  color: {
    getAll:  ()            => inv('color:getAll'),
    add:     (code)        => inv('color:add', code),
    markUsed:(id)          => inv('color:markUsed', id),
    getRecent:()           => inv('color:getRecent'),
    delete:  (id)          => inv('color:delete', id),
  },
  search: {
    all:     (q)           => inv('search:all', q),
  },
  world: {
    getAll:           ()                    => inv('world:getAll'),
    get:              (id)                  => inv('world:get', id),
    create:           (n,m,c)              => inv('world:create', n,m,c),
    update:           (id,n,m,c)           => inv('world:update', id,n,m,c),
    delete:           (id)                 => inv('world:delete', id),
    getDesc:          (wid)               => inv('world:getDesc', wid),
    addDesc:          (wid,t,c)           => inv('world:addDesc', wid,t,c),
    updateDesc:       (id,t,c)            => inv('world:updateDesc', id,t,c),
    deleteDesc:       (id)               => inv('world:deleteDesc', id),
    getNovelLinks:    (wid)              => inv('world:getNovelLinks', wid),
    addNovelLink:     (wid,pid)          => inv('world:addNovelLink', wid,pid),
    removeNovelLink:  (id)              => inv('world:removeNovelLink', id),
    getCharacters:    (wid)             => inv('world:getCharacters', wid),
    createCharacter:  (wid,n,m)         => inv('world:createCharacter', wid,n,m),
    updateCharacter:  (id,n,m)          => inv('world:updateCharacter', id,n,m),
    deleteCharacter:  (id)              => inv('world:deleteCharacter', id),
    setCharLink:      (cid,pid,catid,oid) => inv('world:setCharLink', cid,pid,catid,oid),
    getCharTags:      (cid)             => inv('world:getCharTags', cid),
    setCharTags:      (cid,tags)        => inv('world:setCharTags', cid,tags),
    getCategories:    (wid)             => inv('world:getCategories', wid),
    createCategory:   (wid,n,m)         => inv('world:createCategory', wid,n,m),
    updateCategory:   (id,n,m)          => inv('world:updateCategory', id,n,m),
    deleteCategory:   (id)              => inv('world:deleteCategory', id),
    setCatLink:       (catId,pid,catref) => inv('world:setCatLink', catId,pid,catref),
    getCatObjects:    (catId)           => inv('world:getCatObjects', catId),
    createCatObject:  (catId,n,sym)     => inv('world:createCatObject', catId,n,sym),
    updateCatObject:  (id,n,sym)        => inv('world:updateCatObject', id,n,sym),
    deleteCatObject:  (id)              => inv('world:deleteCatObject', id),
    getObjTags:       (oid)             => inv('world:getObjTags', oid),
    setObjTags:       (oid,tags)        => inv('world:setObjTags', oid,tags),
    getMaps:          (wid)             => inv('world:getMaps', wid),
    createMap:        (wid,n,m)         => inv('world:createMap', wid,n,m),
    updateMap:        (id,n,m)          => inv('world:updateMap', id,n,m),
    deleteMap:        (id)              => inv('world:deleteMap', id),
    setMapLink:       (mid,pid,msrc,aref) => inv('world:setMapLink', mid,pid,msrc,aref),
    getMapTimelines:  (wid)             => inv('world:getMapTimelines', wid),
    createMapTimeline:(wid,mid,n)       => inv('world:createMapTimeline', wid,mid,n),
    updateMapTimeline:(id,mid,n)        => inv('world:updateMapTimeline', id,mid,n),
    deleteMapTimeline:(id)              => inv('world:deleteMapTimeline', id),
    getMaptlEvents:   (tlid)            => inv('world:getMaptlEvents', tlid),
    createMaptlEvent: (tlid,n,ord)      => inv('world:createMaptlEvent', tlid,n,ord),
    updateMaptlEvent: (id,n,ord)        => inv('world:updateMaptlEvent', id,n,ord),
    deleteMaptlEvent: (id)              => inv('world:deleteMaptlEvent', id),
    getMaptlObjs:     (evid)            => inv('world:getMaptlObjs', evid),
    addMaptlObj:      (evid,coid)       => inv('world:addMaptlObj', evid,coid),
    removeMaptlObj:   (id)              => inv('world:removeMaptlObj', id),
    getTags:          (wid)             => inv('world:getTags', wid),
    setTags:          (wid,tags)        => inv('world:setTags', wid,tags),
  },
  game: {
    getAll:             ()                  => inv('game:getAll'),
    get:                (id)               => inv('game:get', id),
    create:             (n,m,c)            => inv('game:create', n,m,c),
    update:             (id,n,m,c)         => inv('game:update', id,n,m,c),
    delete:             (id)               => inv('game:delete', id),
    getDesc:            (gid)             => inv('game:getDesc', gid),
    addDesc:            (gid,t,c)         => inv('game:addDesc', gid,t,c),
    updateDesc:         (id,t,c)          => inv('game:updateDesc', id,t,c),
    deleteDesc:         (id)              => inv('game:deleteDesc', id),
    getNovelLink:       (gid)             => inv('game:getNovelLink', gid),
    setNovelLink:       (gid,pid)         => inv('game:setNovelLink', gid,pid),
    getCharacters:      (gid)             => inv('game:getCharacters', gid),
    createCharacter:    (gid,n,m)         => inv('game:createCharacter', gid,n,m),
    updateCharacter:    (id,n,m)          => inv('game:updateCharacter', id,n,m),
    deleteCharacter:    (id)              => inv('game:deleteCharacter', id),
    setCharLink:        (cid,pid,catid,oid) => inv('game:setCharLink', cid,pid,catid,oid),
    getStats:           (cid)             => inv('game:getStats', cid),
    createStat:         (cid,n,t)         => inv('game:createStat', cid,n,t),
    updateStat:         (id,n,t)          => inv('game:updateStat', id,n,t),
    deleteStat:         (id)              => inv('game:deleteStat', id),
    getStatLevelups:    (cid)             => inv('game:getStatLevelups', cid),
    upsertStatLevelup:  (cid,tid,lv,val)  => inv('game:upsertStatLevelup', cid,tid,lv,val),
    deleteStatLevelup:  (cid,tid,lv)      => inv('game:deleteStatLevelup', cid,tid,lv),
    getCharTags:        (cid)             => inv('game:getCharTags', cid),
    setCharTags:        (cid,tags)        => inv('game:setCharTags', cid,tags),
    getItemCategories:  (gid)             => inv('game:getItemCategories', gid),
    createItemCategory: (gid,n,m)         => inv('game:createItemCategory', gid,n,m),
    updateItemCategory: (id,n,m)          => inv('game:updateItemCategory', id,n,m),
    deleteItemCategory: (id)              => inv('game:deleteItemCategory', id),
    getItemTemplates:   (icid)            => inv('game:getItemTemplates', icid),
    createItemTemplate: (icid,n,t)        => inv('game:createItemTemplate', icid,n,t),
    updateItemTemplate: (id,n,t)          => inv('game:updateItemTemplate', id,n,t),
    deleteItemTemplate: (id)              => inv('game:deleteItemTemplate', id),
    getItems:           (icid)            => inv('game:getItems', icid),
    createItem:         (icid,n,sym)      => inv('game:createItem', icid,n,sym),
    updateItem:         (id,n,sym)        => inv('game:updateItem', id,n,sym),
    deleteItem:         (id)              => inv('game:deleteItem', id),
    getItemAttrs:       (iid)             => inv('game:getItemAttrs', iid),
    upsertItemAttr:     (iid,tid,v)       => inv('game:upsertItemAttr', iid,tid,v),
    getItemTags:        (iid)             => inv('game:getItemTags', iid),
    setItemTags:        (iid,tags)        => inv('game:setItemTags', iid,tags),
    getStories:         (gid)             => inv('game:getStories', gid),
    createStory:        (gid,n,m)         => inv('game:createStory', gid,n,m),
    updateStory:        (id,n,m)          => inv('game:updateStory', id,n,m),
    deleteStory:        (id)              => inv('game:deleteStory', id),
    getDialogues:       (sid)             => inv('game:getDialogues', sid),
    createDialogue:     (sid,n,m,x,y)     => inv('game:createDialogue', sid,n,m,x,y),
    updateDialogue:     (id,n,m,x,y)      => inv('game:updateDialogue', id,n,m,x,y),
    deleteDialogue:     (id)              => inv('game:deleteDialogue', id),
    updateDialoguePos:  (id,x,y)          => inv('game:updateDialoguePos', id,x,y),
    getDialogueEdges:   (sid)             => inv('game:getDialogueEdges', sid),
    createDialogueEdge: (fid,tid,cond)    => inv('game:createDialogueEdge', fid,tid,cond),
    deleteDialogueEdge: (id)              => inv('game:deleteDialogueEdge', id),
    getDialogueLines:   (did)             => inv('game:getDialogueLines', did),
    createDialogueLine: (did,spk,txt,ord) => inv('game:createDialogueLine', did,spk,txt,ord),
    updateDialogueLine: (id,spk,txt,ord)  => inv('game:updateDialogueLine', id,spk,txt,ord),
    deleteDialogueLine: (id)              => inv('game:deleteDialogueLine', id),
    getFuncCategories:  (gid)             => inv('game:getFuncCategories', gid),
    createFuncCategory: (gid,n,t)         => inv('game:createFuncCategory', gid,n,t),
    updateFuncCategory: (id,n,t)          => inv('game:updateFuncCategory', id,n,t),
    deleteFuncCategory: (id)              => inv('game:deleteFuncCategory', id),
    getFunctions:       (fcid)            => inv('game:getFunctions', fcid),
    createFunction:     (fcid,n,tpl,cond,eff) => inv('game:createFunction', fcid,n,tpl,cond,eff),
    updateFunction:     (id,n,tpl,cond,eff) => inv('game:updateFunction', id,n,tpl,cond,eff),
    deleteFunction:     (id)              => inv('game:deleteFunction', id),
    getTags:            (gid)             => inv('game:getTags', gid),
    setTags:            (gid,tags)        => inv('game:setTags', gid,tags),
  },
  window: {
    minimize:       () => inv('window:minimize'),
    toggleMaximize: () => inv('window:toggleMaximize'),
    close:          () => inv('window:close'),
  },
});
