const { contextBridge, ipcRenderer } = require('electron');
const inv = (ch, ...a) => ipcRenderer.invoke(ch, ...a);

contextBridge.exposeInMainWorld('api', {
  db: {
    exportFile: ()          => inv('db:exportFile'),
    importFileMerge: ()     => inv('db:importFileMerge'),
  },
  folder: {
    getAll:  ()            => inv('folder:getAll'),
    create:  (n,m,c)       => inv('folder:create', n,m,c),
    update:  (id,n,m,c)    => inv('folder:update', id,n,m,c),
    delete:  (id)          => inv('folder:delete', id),
  },
  project: {
    getAll:  (fid)         => inv('project:getAll', fid),
    get:     (id)          => inv('project:get', id),
    create:  (data)        => inv('project:create', data),
    update:  (id,data)     => inv('project:update', id, data),
    delete:  (id)          => inv('project:delete', id),
    getDesc: (pid)         => inv('project:getDesc', pid),
    addDesc: (pid,n,t)     => inv('project:addDesc', pid,n,t),
    updDesc: (id,n,t)      => inv('project:updDesc', id,n,t),
    delDesc: (id)          => inv('project:delDesc', id),
    getTags: (pid)        => inv('project:getTags', pid),
    setTags: (pid,tags)   => inv('project:setTags', pid,tags),
    addTag: (pid,tid)     => inv('project:addTag', pid,tid),
    removeTag: (pid,tid)  => inv('project:removeTag', pid,tid),
    getAllUsedTags: (pid)  => inv('project:getAllUsedTags', pid),
  },
  category: {
    getAll:  (pid)         => inv('category:getAll', pid),
    create:  (pid,n,c)     => inv('category:create', pid,n,c),
    update:  (id,n,c)      => inv('category:update', id,n,c),
    delete:  (id)          => inv('category:delete', id),
  },
  template: {
    getAll:  (cid)         => inv('template:getAll', cid),
    create:  (cid,d,t)     => inv('template:create', cid,d,t),
    update:  (id,d,t)      => inv('template:update', id,d,t),
    delete:  (id)          => inv('template:delete', id),
  },
  object: {
    getAll:  (cid)         => inv('object:getAll', cid),
    get:     (id)          => inv('object:get', id),
    create:  (pid,cid,n,c) => inv('object:create', pid,cid,n,c),
    update:  (id,n,c)      => inv('object:update', id,n,c),
    updateNote: (id,note)  => inv('object:updateNote', id,note),
    delete:  (id)          => inv('object:delete', id),
    getAttrs:(oid)         => inv('object:getAttrs', oid),
    upsertAttr:(oid,tid,v) => inv('object:upsertAttr', oid,tid,v),
    getCategoryAttrs:(cid) => inv('object:getCategoryAttrs', cid),
    getTags: (oid)         => inv('object:getTags', oid),
    setTags: (oid,tags)    => inv('object:setTags', oid,tags),
    addTag: (oid,tid)      => inv('object:addTag', oid,tid),
    removeTag: (oid,tid)   => inv('object:removeTag', oid,tid),
  },
  timeline: {
    getAll:  (pid)        => inv('timeline:getAll', pid),
    create:  (pid,n,c)    => inv('timeline:create', pid,n,c),
    update:  (id,n,c)     => inv('timeline:update', id,n,c),
    delete:  (id)         => inv('timeline:delete', id),
    getOrCreateDate: (d,m,y,hh,mm) => inv('timeline:getOrCreateDate', d,m,y,hh,mm),
    getEvents: (tlid)     => inv('timeline:getEvents', tlid),
    createEvent: (tlid,n,s,e,c,story) => inv('timeline:createEvent', tlid,n,s,e,c,story),
    updateEvent: (id,n,s,e,c,story)  => inv('timeline:updateEvent', id,n,s,e,c,story),
    updateEventStory: (id,story) => inv('timeline:updateEventStory', id,story),
    deleteEvent: (id)     => inv('timeline:deleteEvent', id),
    getEventTags: (eid)   => inv('timeline:getEventTags', eid),
    setEventTags: (eid,tags) => inv('timeline:setEventTags', eid,tags),
    addEventTag: (eid,tid) => inv('timeline:addEventTag', eid,tid),
    removeEventTag: (eid,tid) => inv('timeline:removeEventTag', eid,tid),
  },
  relation: {
    getTypes: ()          => inv('relation:getTypes'),
    createType: (n,c)     => inv('relation:createType', n,c),
    updateType: (id,n,c)  => inv('relation:updateType', id,n,c),
    deleteType: (id)      => inv('relation:deleteType', id),
    getOBOB: (pid)        => inv('relation:getOBOB', pid),
    createOBOB: (pid,tid,c,f,t) => inv('relation:createOBOB', pid,tid,c,f,t),
    deleteOBOB: (id)      => inv('relation:deleteOBOB', id),
    update: (id,tid,c)     => inv('relation:update', id,tid,c),
    getOBTL: (pid)        => inv('relation:getOBTL', pid),
    createOBTL: (pid,tid,c,f,t) => inv('relation:createOBTL', pid,tid,c,f,t),
    deleteOBTL: (id)      => inv('relation:deleteOBTL', id),
    getTLTL: (pid)        => inv('relation:getTLTL', pid),
    createTLTL: (pid,tid,c,f,t) => inv('relation:createTLTL', pid,tid,c,f,t),
    deleteTLTL: (id)      => inv('relation:deleteTLTL', id),
    getProjectObjects: (pid) => inv('relation:getProjectObjects', pid),
    getProjectEvents: (pid)  => inv('relation:getProjectEvents', pid),
    getEventLinks: (eid)     => inv('relation:getEventLinks', eid),
  },
  map: {
    getAll: (pid)            => inv('map:getAll', pid),
    create: (pid,n,c)        => inv('map:create', pid,n,c),
    update: (id,n,c)         => inv('map:update', id,n,c),
    delete: (id)             => inv('map:delete', id),
    getAreas: (mid)          => inv('map:getAreas', mid),
    createArea: (mid,n,c)    => inv('map:createArea', mid,n,c),
    updateArea: (id,n,c)     => inv('map:updateArea', id,n,c),
    deleteArea: (id)         => inv('map:deleteArea', id),
    getPoints: (aid)         => inv('map:getPoints', aid),
    setPoints: (aid,points)  => inv('map:setPoints', aid, points),
  },
  hashtag: {
    getAll:  ()           => inv('hashtag:getAll'),
    create:  (n,c)        => inv('hashtag:create', n,c),
    update:  (id,n,c)     => inv('hashtag:update', id,n,c),
    delete:  (id)         => inv('hashtag:delete', id),
    getObjectsByTag: (tagId, projectId) => inv('hashtag:getObjectsByTag', tagId, projectId),
    getEventsByTag: (tagId, projectId)  => inv('hashtag:getEventsByTag', tagId, projectId),
  },
  color: {
    getAll:  ()            => inv('color:getAll'),
    add:     (code)        => inv('color:add', code),
    markUsed:(id)          => inv('color:markUsed', id),
    getRecent:()           => inv('color:getRecent'),
    delete:  (id)          => inv('color:delete', id),
  },
  search: {
    all:     (q)           => inv('search:all', q),
  },
  world: {
    getAll:                  ()              => inv('world:getAll'),
    get:                     (id)            => inv('world:get', id),
    create:                  (code,n,m,c)    => inv('world:create', code,n,m,c),
    update:                  (id,code,n,m,c) => inv('world:update', id,code,n,m,c),
    delete:                  (id)            => inv('world:delete', id),

    getNovels:               (wid)           => inv('world:getNovels', wid),
    getLinkableProjects:     (wid)           => inv('world:getLinkableProjects', wid),
    addNovel:                (wid,pid)       => inv('world:addNovel', wid,pid),
    removeNovel:             (id)            => inv('world:removeNovel', id),
    setNovelCharCat:         (wnid,catref)   => inv('world:setNovelCharCat', wnid,catref),

    // World-owned ("original") category→object→attribute→template
    origCat: {
      getAll:  (wid)    => inv('world:origCatGetAll', wid),
      create:  (wid,n,c)=> inv('world:origCatCreate', wid,n,c),
      update:  (id,n,c) => inv('world:origCatUpdate', id,n,c),
      delete:  (id)     => inv('world:origCatDelete', id),
    },
    origTmpl: {
      getAll:  (cid)    => inv('world:origTmplGetAll', cid),
      create:  (cid,d,t)=> inv('world:origTmplCreate', cid,d,t),
      update:  (id,d,t) => inv('world:origTmplUpdate', id,d,t),
      delete:  (id)     => inv('world:origTmplDelete', id),
    },
    origObj: {
      getAll:     (cid)     => inv('world:origObjGetAll', cid),
      get:        (id)      => inv('world:origObjGet', id),
      create:     (wid,cid,n,c) => inv('world:origObjCreate', wid,cid,n,c),
      update:     (id,n,c)  => inv('world:origObjUpdate', id,n,c),
      updateNote: (id,note) => inv('world:origObjUpdateNote', id,note),
      delete:     (id)      => inv('world:origObjDelete', id),
      getAttrs:   (oid)     => inv('world:origObjGetAttrs', oid),
      upsertAttr: (oid,tid,v) => inv('world:origObjUpsertAttr', oid,tid,v),
    },
    desc: {
      getAll:  (wid)    => inv('world:getDesc', wid),
      add:     (wid,n,t)=> inv('world:addDesc', wid,n,t),
      update:  (id,n,t) => inv('world:updDesc', id,n,t),
      delete:  (id)     => inv('world:delDesc', id),
    },

    getTags:                 (wid)           => inv('world:getTags', wid),
    setTags:                 (wid,tags)      => inv('world:setTags', wid,tags),
    getCharTags:             (cid)           => inv('world:getCharTags', cid),
    setCharTags:             (cid,tags)      => inv('world:setCharTags', cid,tags),
    getAllUsedTags:          (wid)           => inv('world:getAllUsedTags', wid),
    getCharactersByTag:      (tid,wid)       => inv('world:getCharactersByTag', tid,wid),

    getCharacters:           (wid)           => inv('world:getCharacters', wid),
    createCharacter:         (wid,n,sym,c)   => inv('world:createCharacter', wid,n,sym,c),
    updateCharacter:         (id,n,sym,c)    => inv('world:updateCharacter', id,n,sym,c),
    deleteCharacter:         (id)            => inv('world:deleteCharacter', id),
    getCharLinks:            (cid)           => inv('world:getCharLinks', cid),
    getLinkableCharObjects:  (wid,cid)       => inv('world:getLinkableCharObjects', wid,cid),
    addCharLink:             (cid,oref)      => inv('world:addCharLink', cid,oref),
    removeCharLink:          (id)            => inv('world:removeCharLink', id),

    getCategories:           (wid)           => inv('world:getCategories', wid),
    getLinkableCategories:   (wid,forChars)  => inv('world:getLinkableCategories', wid,forChars),
    addCategory:             (wid,catref)    => inv('world:addCategory', wid,catref),
    removeCategory:          (id)            => inv('world:removeCategory', id),

    getObjects:              (wcid)          => inv('world:getObjects', wcid),
    updateObjectSymbol:      (id,sym,custom) => inv('world:updateObjectSymbol', id,sym,custom),
    getSymbolCollection:     ()              => inv('world:getSymbolCollection'),

    getMaps:                 (wid)           => inv('world:getMaps', wid),
    getLinkableMaps:         (wid)           => inv('world:getLinkableMaps', wid),
    addMap:                  (wid,mref)      => inv('world:addMap', wid,mref),
    removeMap:               (id)            => inv('world:removeMap', id),
    getMapAreas:             (wmid)          => inv('world:getMapAreas', wmid),

    getTimelines:            (wid)           => inv('world:getTimelines', wid),
    createTimeline:          (wid,n,wmref)   => inv('world:createTimeline', wid,n,wmref),
    updateTimeline:          (id,n,wmref)    => inv('world:updateTimeline', id,n,wmref),
    deleteTimeline:          (id)            => inv('world:deleteTimeline', id),

    getEvents:               (tlid)          => inv('world:getEvents', tlid),
    createEvent:             (tlid,d,mo,y,hr,mi) => inv('world:createEvent', tlid,d,mo,y,hr,mi),
    deleteEvent:             (id)            => inv('world:deleteEvent', id),

    getEventObjects:         (evid)          => inv('world:getEventObjects', evid),
    getPlaceableObjects:     (wid)           => inv('world:getPlaceableObjects', wid),
    getPlaceableCharacters:  (wid)           => inv('world:getPlaceableCharacters', wid),
    addEventObject:          (evid,oref,cref,x,y) => inv('world:addEventObject', evid,oref,cref,x,y),
    updateEventObjectPoint:  (id,x,y)        => inv('world:updateEventObjectPoint', id,x,y),
    removeEventObject:       (id)            => inv('world:removeEventObject', id),
  },
  game: {
    getAll:             ()                => inv('game:getAll'),
    get:                (id)              => inv('game:get', id),
    create:             (n,cn,m,c)        => inv('game:create', n,cn,m,c),
    update:             (id,n,cn,m,c)     => inv('game:update', id,n,cn,m,c),
    delete:             (id)              => inv('game:delete', id),
    getNovelLink:       (gid)             => inv('game:getNovelLink', gid),
    setNovelLink:       (gid,pid)         => inv('game:setNovelLink', gid,pid),
    getCategories:      (gid)             => inv('game:getCategories', gid),
    addCategory:        (gid,catid)       => inv('game:addCategory', gid,catid),
    removeCategory:     (gid,catid)       => inv('game:removeCategory', gid,catid),
    addCatObject:       (gid,catid,oid)   => inv('game:addCatObject', gid,catid,oid),
    removeCatObject:    (gid,catid,oid)   => inv('game:removeCatObject', gid,catid,oid),
    getImportedObjects: (gid)             => inv('game:getImportedObjects', gid),
    getCategoryObjects: (gid,catid)       => inv('game:getCategoryObjects', gid,catid),
    getCharacters:      (gid)             => inv('game:getCharacters', gid),
    createCharacter:    (gid,n,ol,c)      => inv('game:createCharacter', gid,n,ol,c),
    updateCharacter:    (id,n,ol,c)       => inv('game:updateCharacter', id,n,ol,c),
    deleteCharacter:    (id)              => inv('game:deleteCharacter', id),
    getCharTemplates:   (gid)             => inv('game:getCharTemplates', gid),
    createCharTemplate: (gid,n,t,lv)      => inv('game:createCharTemplate', gid,n,t,lv),
    updateCharTemplate: (id,n,t,lv)       => inv('game:updateCharTemplate', id,n,t,lv),
    deleteCharTemplate: (id)              => inv('game:deleteCharTemplate', id),
    getCharAttrs:       (cid)             => inv('game:getCharAttrs', cid),
    upsertCharAttr:     (cid,tid,lv,txt)  => inv('game:upsertCharAttr', cid,tid,lv,txt),
    deleteCharAttr:     (cid,tid,lv)      => inv('game:deleteCharAttr', cid,tid,lv),
    getCharElements:    (cid)             => inv('game:getCharElements', cid),
    setCharElements:    (cid,eids)        => inv('game:setCharElements', cid,eids),
    getCharTags:        (cid)             => inv('game:getCharTags', cid),
    setCharTags:        (cid,tags)        => inv('game:setCharTags', cid,tags),
    getCollections:     (gid)             => inv('game:getCollections', gid),
    createCollection:   (gid,n,c)         => inv('game:createCollection', gid,n,c),
    updateCollection:   (id,n,c)          => inv('game:updateCollection', id,n,c),
    deleteCollection:   (id)              => inv('game:deleteCollection', id),
    getColTemplates:    (colid)           => inv('game:getColTemplates', colid),
    createColTemplate:  (colid,n,t,lv)    => inv('game:createColTemplate', colid,n,t,lv),
    updateColTemplate:  (id,n,t,lv)       => inv('game:updateColTemplate', id,n,t,lv),
    deleteColTemplate:  (id)              => inv('game:deleteColTemplate', id),
    getColElements:     (colid)           => inv('game:getColElements', colid),
    createColElement:   (colid,n,c)       => inv('game:createColElement', colid,n,c),
    updateColElement:   (id,n,c)          => inv('game:updateColElement', id,n,c),
    deleteColElement:   (id)              => inv('game:deleteColElement', id),
    getElementAttrs:    (eid)             => inv('game:getElementAttrs', eid),
    upsertElementAttr:  (eid,tid,lv,txt)  => inv('game:upsertElementAttr', eid,tid,lv,txt),
    deleteElementAttr:  (eid,tid,lv)      => inv('game:deleteElementAttr', eid,tid,lv),
    getElementTags:     (eid)             => inv('game:getElementTags', eid),
    setElementTags:     (eid,tags)        => inv('game:setElementTags', eid,tags),
    getStories:         (gid)             => inv('game:getStories', gid),
    createStory:        (gid,n,m,c)       => inv('game:createStory', gid,n,m,c),
    updateStory:        (id,n,m,c)        => inv('game:updateStory', id,n,m,c),
    deleteStory:        (id)              => inv('game:deleteStory', id),
    getDialogues:       (sid)             => inv('game:getDialogues', sid),
    createDialogue:     (sid,n,m,c,x,y)   => inv('game:createDialogue', sid,n,m,c,x,y),
    updateDialogue:     (id,n,m,c)        => inv('game:updateDialogue', id,n,m,c),
    updateDialoguePos:  (id,x,y)          => inv('game:updateDialoguePos', id,x,y),
    deleteDialogue:     (id)              => inv('game:deleteDialogue', id),
    getStorylines:      (sid)             => inv('game:getStorylines', sid),
    createStoryline:    (sid,fid,tid,c)   => inv('game:createStoryline', sid,fid,tid,c),
    deleteStoryline:    (id)              => inv('game:deleteStoryline', id),
    getConversations:   (did)             => inv('game:getConversations', did),
    createConversation: (did,cid,txt)     => inv('game:createConversation', did,cid,txt),
    updateConversation: (id,cid,txt)      => inv('game:updateConversation', id,cid,txt),
    deleteConversation: (id)              => inv('game:deleteConversation', id),
    moveConversation:   (id,dir)          => inv('game:moveConversation', id,dir),
    getTags:            (gid)             => inv('game:getTags', gid),
    setTags:            (gid,tags)        => inv('game:setTags', gid,tags),
    getUsedTags:        (gid)             => inv('game:getUsedTags', gid),
    getCharsByTag:      (tid,gid)         => inv('game:getCharsByTag', tid,gid),
    getElementsByTag:   (tid,gid)         => inv('game:getElementsByTag', tid,gid),
  },
  library: {
    getProjects:        ()                => inv('library:getProjects'),
    createProject:      (n,m,c)          => inv('library:createProject', n,m,c),
    updateProject:      (id,n,m,c)       => inv('library:updateProject', id,n,m,c),
    deleteProject:      (id)             => inv('library:deleteProject', id),
    getDescriptions:    (lid)            => inv('library:getDescriptions', lid),
    createDescription:  (lid,t,c)        => inv('library:createDescription', lid,t,c),
    updateDescription:  (id,t,c)         => inv('library:updateDescription', id,t,c),
    deleteDescription:  (id)             => inv('library:deleteDescription', id),
    getWorldLinks:      (lid)            => inv('library:getWorldLinks', lid),
    addWorldLink:       (lid,wid)        => inv('library:addWorldLink', lid,wid),
    removeWorldLink:    (id)             => inv('library:removeWorldLink', id),
    getSeries:          (lid)            => inv('library:getSeries', lid),
    createSeries:       (lid,n,m)        => inv('library:createSeries', lid,n,m),
    updateSeries:       (id,n,m)         => inv('library:updateSeries', id,n,m),
    deleteSeries:       (id)             => inv('library:deleteSeries', id),
    getSeriesDescs:     (sid)            => inv('library:getSeriesDescs', sid),
    createSeriesDesc:   (sid,t,c)        => inv('library:createSeriesDesc', sid,t,c),
    updateSeriesDesc:   (id,t,c)         => inv('library:updateSeriesDesc', id,t,c),
    deleteSeriesDesc:   (id)             => inv('library:deleteSeriesDesc', id),
    getSeriesNovels:    (sid)            => inv('library:getSeriesNovels', sid),
    addSeriesNovel:     (sid,pid)        => inv('library:addSeriesNovel', sid,pid),
    removeSeriesNovel:  (id)             => inv('library:removeSeriesNovel', id),
    getSeriesChars:     (sid)            => inv('library:getSeriesChars', sid),
    addSeriesChar:      (sid,oid)        => inv('library:addSeriesChar', sid,oid),
    removeSeriesChar:   (id)             => inv('library:removeSeriesChar', id),
    getSeriesObjects:   (sid)            => inv('library:getSeriesObjects', sid),
    addSeriesObject:    (sid,oid)        => inv('library:addSeriesObject', sid,oid),
    removeSeriesObject: (id)             => inv('library:removeSeriesObject', id),
    getSeriesTags:      (sid)            => inv('library:getSeriesTags', sid),
    toggleSeriesTag:    (sid,hid)        => inv('library:toggleSeriesTag', sid,hid),
    getDocs:            (sid)            => inv('library:getDocs', sid),
    createDoc:          (sid,n)          => inv('library:createDoc', sid,n),
    getDoc:             (id)             => inv('library:getDoc', id),
    updateDoc:          (id,n,cj)        => inv('library:updateDoc', id,n,cj),
    deleteDoc:          (id)             => inv('library:deleteDoc', id),
    getDocTags:         (did)            => inv('library:getDocTags', did),
    toggleDocTag:       (did,hid)        => inv('library:toggleDocTag', did,hid),
    exportPdf:          (html,name)      => inv('library:exportPdf', html,name),
    exportDocx:         (blocks,name)    => inv('library:exportDocx', blocks,name),
  },
  sage: {
    getDataSize:     () => inv('sage:getDataSize'),
    getObjectAmounts:() => inv('sage:getObjectAmounts'),
    getLinkerList:   () => inv('sage:getLinkerList'),
    getLinkerGraph:  () => inv('sage:getLinkerGraph'),
  },
  window: {
    minimize:       () => inv('window:minimize'),
    toggleMaximize: () => inv('window:toggleMaximize'),
    close:          () => inv('window:close'),
  },
});
